MainWidget:


<MainWidget>:
    Button:
        text: "Choose Workday File"
        size: 400, 100
        pos: 100, 400

    Button:
        text: "Choose Concur File"
        size: 400, 100
        pos: 100, 200
        color: 0, 0, 1, 1




 #   FileChooserListView:
 #       id:filechooser
 #       on_selection:MainWidget.selected(filechooser.selection)

 #   Image:
 #       id:my_file
 #       source:""